import { dirname, join } from 'path';
import type { INestApplication } from '@nestjs/common';
import type { Express } from 'express';
import { AuthService } from '@thallesp/nestjs-better-auth';
import { apiReference } from '@scalar/express-api-reference';
import { DocumentBuilder, OpenAPIObject, SwaggerModule } from '@nestjs/swagger';
import type { Auth } from '../../modules/auth/auth.config';

const DOCS_PATH = '/api/docs';
const OPENAPI_JSON_PATH = '/api/openapi.json';
const SCALAR_BUNDLE_PATH = `${DOCS_PATH}/scalar-standalone.js`;
const BETTER_AUTH_BASE_PATH = '/api/auth';
const AUTHENTICATION_TAG = 'Authentication';
const AUTHENTICATION_ADMIN_TAG = 'Authentication Admin';
const BETTER_AUTH_DEFAULT_TAG = 'Default';
const BETTER_AUTH_ADMIN_TAG = 'Admin';
const HEALTH_TAG = 'health';
const HEALTH_TAG_RENAMED = 'Health';
const SESSION_COOKIE_NAME = 'better-auth.session_token';

interface BetterAuthOpenApiDocument {
  paths?: Record<string, unknown>;
  components?: { schemas?: Record<string, unknown> };
}

/**
 * Sets up `/api/docs` as a single Scalar reference page and `/api/openapi.json`
 * as the OpenAPI document backing it, merging two independently generated
 * documents into one:
 *
 *  - The NestJS document: generated by @nestjs/swagger from decorated
 *    controllers (currently just `GET /api/health`).
 *  - Better Auth's document: generated directly by Better Auth's own
 *    `openAPI()` plugin, covering every Better Auth endpoint (core,
 *    email/password, session, and the admin plugin) — generated by Better
 *    Auth itself on every request rather than hand-written, so it never
 *    drifts out of sync with Better Auth's actual routes.
 *
 * Better Auth's paths are relative to its own `basePath` (e.g. `/sign-in/email`)
 * and are prefixed with `/api/auth` here so they resolve against the same
 * server the merged document is served from. Better Auth already tags its
 * own operations (`Admin` for the admin-plugin endpoints, `Default` for
 * everything else); these are renamed to `Authentication` and
 * `Authentication Admin` respectively, and the NestJS document's `health`
 * tag is renamed to `Health`, so every tag in the merged page reads as a
 * proper category name. Both the tag list and the operations within each
 * tag are sorted alphabetically (`tagsSorter`/`operationsSorter`), which
 * also keeps `Authentication Admin` grouped directly under `Authentication`.
 * Better Auth's document is OpenAPI 3.1-shaped (it uses the `type: [T, "null"]` nullable
 * form, invalid under 3.0), so the merged document declares `openapi: 3.1.0`
 * — a NestJS 3.0.0 document is valid content under 3.1 as well, so nothing
 * is lost by raising the declared version.
 *
 * Better Auth's document is generated in-process via `AuthService.api
 * .generateOpenAPISchema()` (the exact function backing its own
 * `/api/auth/open-api/generate-schema` route) rather than an HTTP call to
 * that route, since this runs during bootstrap before the server is
 * listening.
 *
 * `@scalar/api-reference`'s standalone browser bundle is served from this
 * app (via the `cdn` option) instead of `@scalar/express-api-reference`'s
 * default jsDelivr CDN, so the page has no runtime dependency on a third
 * party.
 */
export async function setupSwagger(app: INestApplication): Promise<void> {
  const config = new DocumentBuilder()
    .setTitle('Supabase Heartbeat API')
    .setDescription('API for managing Supabase Heartbeat.')
    .setVersion('0.1.0')
    .addCookieAuth(SESSION_COOKIE_NAME, {
      type: 'apiKey',
      in: 'cookie',
      name: SESSION_COOKIE_NAME,
      description:
        "Better Auth's session cookie, set after signing in via " +
        '/api/auth/sign-in/email. The application authenticates every ' +
        'request through this cookie, not a bearer token.',
    })
    .build();
  const appDocument = SwaggerModule.createDocument(app, config);
  const authService = app.get(AuthService<Auth>);

  const scalarBundlePath = await getScalarStandaloneBundleFSPath();
  const expressApp = app.getHttpAdapter().getInstance() as Express;

  expressApp.get(OPENAPI_JSON_PATH, async (_req, res) => {
    const betterAuthDocument =
      (await authService.api.generateOpenAPISchema()) as BetterAuthOpenApiDocument;
    res.json(mergeOpenApiDocuments(appDocument, betterAuthDocument));
  });

  expressApp.get(
    DOCS_PATH,
    apiReference({
      cdn: SCALAR_BUNDLE_PATH,
      pageTitle: 'Supabase Heartbeat API Docs',
      url: OPENAPI_JSON_PATH,
      tagsSorter: 'alpha',
      operationsSorter: 'alpha',
    }),
  );
  expressApp.get(SCALAR_BUNDLE_PATH, (_req, res) => {
    res.type('application/javascript').sendFile(scalarBundlePath);
  });
}

function mergeOpenApiDocuments(
  appDocument: OpenAPIObject,
  betterAuthDocument: BetterAuthOpenApiDocument,
): Record<string, unknown> {
  const betterAuthTagRenames = {
    [BETTER_AUTH_DEFAULT_TAG]: AUTHENTICATION_TAG,
    [BETTER_AUTH_ADMIN_TAG]: AUTHENTICATION_ADMIN_TAG,
  };
  const prefixedBetterAuthPaths = Object.fromEntries(
    Object.entries(
      retagPaths(betterAuthDocument.paths, betterAuthTagRenames),
    ).map(([path, item]) => [`${BETTER_AUTH_BASE_PATH}${path}`, item]),
  );

  return {
    ...appDocument,
    openapi: '3.1.0',
    paths: {
      ...retagPaths(appDocument.paths, { [HEALTH_TAG]: HEALTH_TAG_RENAMED }),
      ...prefixedBetterAuthPaths,
    },
    components: {
      ...appDocument.components,
      schemas: {
        ...appDocument.components?.schemas,
        ...betterAuthDocument.components?.schemas,
      },
    },
  };
}

function retagPaths(
  paths: Record<string, unknown> | undefined,
  tagRenames: Record<string, string>,
): Record<string, unknown> {
  return Object.fromEntries(
    Object.entries(paths ?? {}).map(([path, item]) => [
      path,
      retagOperations(item as Record<string, unknown>, tagRenames),
    ]),
  );
}

function retagOperations(
  pathItem: Record<string, unknown>,
  tagRenames: Record<string, string>,
): Record<string, unknown> {
  return Object.fromEntries(
    Object.entries(pathItem).map(([method, operation]) => [
      method,
      typeof operation === 'object' && operation !== null
        ? { ...operation, tags: renameTags(operation, tagRenames) }
        : operation,
    ]),
  );
}

function renameTags(
  operation: object,
  tagRenames: Record<string, string>,
): string[] {
  const tags = (operation as { tags?: string[] }).tags ?? [];
  return tags.map((tag) => tagRenames[tag] ?? tag);
}

/**
 * `@scalar/api-reference`'s standalone bundle (`dist/browser/standalone.js`)
 * is a plain asset file with no package `exports` entry of its own, so it
 * cannot be resolved by specifier — only the package's main entry can. Its
 * install location also cannot be guessed relative to `process.cwd()`:
 * Yarn's node-modules linker hoists this package to the monorepo root, not
 * `apps/api/node_modules`.
 *
 * `createRequire` is used instead of a top-level `import`/`require` because
 * this file is compiled twice with different module targets (CJS for the
 * Nest build, ESM for ts-jest's test transform) — `createRequire` and the
 * `module` it comes from work identically under both, unlike `require`
 * (undefined under Jest's ESM transform) or `import.meta.resolve`
 * (a compile error in files that build to CommonJS output).
 */
async function getScalarStandaloneBundleFSPath(): Promise<string> {
  const { createRequire } = await import('module');
  const require = createRequire(`${process.cwd()}/package.json`);
  const mainEntryPath = require.resolve('@scalar/api-reference');
  return join(dirname(mainEntryPath), 'browser', 'standalone.js');
}
